name: release
on:
  push:
    branches: [ master, integration ]
  pull_request:
    branches: [ master, integration ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.32
    steps:
      - uses: actions/checkout@v2
      - uses: perl-actions/install-with-cpanm@v1
        with:
          sudo: false
      - run: apt-get --yes install wkhtmltopdf
      - run: |-
          cpanm --from https://cpan.metacpan.org/ --notest --force --skip-satisfied \
            --with-develop --with-all-features --installdeps . Devel::Cover::Report::Codecov
      - run: ./bin/build.pl -c
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |-
          set -x
          assets=()
          for asset in ./build/*
          do
            assets+=("-a" "$asset")
          done
          now=$( date '+%Y-%m-%d %H:%M:%S %Z' )
          sha7=$( echo ${GITHUB_SHA} | cut -c1-7 )
          branch=$( echo ${GITHUB_REF} | cut -c12-100 )
          [[ ${branch} == 'master' ]] && p="" || p="--prerelease"
          wget https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz
          tar xvfpz hub-linux-amd64-2.14.2.tgz
          ./hub-linux-amd64-2.14.2/bin/hub release create "${assets[@]}" $p -m "$now - $branch" "$sha7"
