name: release
on:
  push:
    branches: [ master, integration ]
  pull_request:
    branches: [ master, integration ]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gryphonshafer/GitHub-MD-Book@v4
        with:
          settings: .github/github-md-book.yml
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |-
          set -x
          assets=()
          for asset in ./output/*
          do
            assets+=("-a" "$asset")
          done
          now=$( date '+%Y-%m-%d %H:%M:%S %Z' )
          time=$( date '+%s' )
          branch=$( echo ${GITHUB_REF} | cut -c12-100 )
          [[ ${branch} == 'master' ]] && p="" || p="--prerelease"
          echo $GITHUB_TOKEN
          wget https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz
          tar xvfpz hub-linux-amd64-2.14.2.tgz
          ./hub-linux-amd64-2.14.2/bin/hub release create "${assets[@]}" $p -m "$now - $branch" "$time"
